### ISSUE TITLE
Doesnt install correctly on RedHat / Rocky

### ISSUE THREAD

**Issue by tpelser** [FZJ-IEK3-VSA/glaes#16]
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Rocky
Description:    Rocky Linux release 8.8 (Green Obsidian)
Release:        8.8
Codename:       GreenObsidian

x86_64 GNU/Linux

Installing via conda-forge appears to work. But then in python, importing glaes fails:

>>> import glaes as gl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fast/home/t-pelser/micromamba/envs/glaes/lib/python3.8/site-packages/glaes/__init__.py", line 5, in <module>
    from .core import util
  File "/fast/home/t-pelser/micromamba/envs/glaes/lib/python3.8/site-packages/glaes/core/util.py", line 1, in <module>
    import geokit as gk
  File "/fast/home/t-pelser/micromamba/envs/glaes/lib/python3.8/site-packages/geokit/__init__.py", line 27, in <module>
    import geokit.util
  File "/fast/home/t-pelser/micromamba/envs/glaes/lib/python3.8/site-packages/geokit/util.py", line 6, in <module>
    from geokit.core.util import (
  File "/fast/home/t-pelser/micromamba/envs/glaes/lib/python3.8/site-packages/geokit/core/util.py", line 7, in <module>
    from osgeo import gdal, ogr, osr
  File "/fast/home/t-pelser/micromamba/envs/glaes/lib/python3.8/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/fast/home/t-pelser/micromamba/envs/glaes/lib/python3.8/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/fast/home/t-pelser/micromamba/envs/glaes/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/fast/home/t-pelser/micromamba/envs/glaes/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libnsl.so.1: cannot open shared object file: No such file or directory

**Comment by chrisjwin** [comment]
seems to work after new tests by @tpelser

**Comment by chrisjwin** [comment]
closed
